-- L-Stack (Learning Stack) — Soru Havuzu (376 soru)
-- schema.sql çalıştırıldıktan sonra bu dosyayı SQL Editor'da çalıştır

insert into soru_havuzu (soru_metni, kategori) values

-- FELSEFE (15 soru)
('Özgür irade gerçekten var mı, yoksa tüm kararlarımız önceden belirlenmiş mi?', 'felsefe'),
('Mutluluk bir amaç mı yoksa yan ürün mü?', 'felsefe'),
('Bir insanı "iyi" yapan şey nedir?', 'felsefe'),
('Hiç kimse görmeseydi yine de doğru olanı yapar mıydın?', 'felsefe'),
('Anlamlı bir hayat ile mutlu bir hayat arasında seçim yapmak zorunda kalsan hangisini seçerdin?', 'felsefe'),
('Bilmediğini bilmek ne anlama gelir?', 'felsefe'),
('Sessizlik sana ne anlatıyor?', 'felsefe'),
('Zaman gerçek mi yoksa insan zihninin bir yanılsaması mı?', 'felsefe'),
('Acı çekmek insanı daha mı güçlü yapar yoksa bu sadece bir teselli mi?', 'felsefe'),
('Herkes aynı şeyi "kırmızı" olarak mı görüyor?', 'felsefe'),
('Adalet ile merhamet çeliştiğinde hangisi önce gelir?', 'felsefe'),
('Ölüm hayata anlam mı katar yoksa anlamı mı çalar?', 'felsefe'),
('Bir paradoks seni derinden düşündürdü mü? Hangisiydi?', 'felsefe'),
('Kendini tanımak mümkün mü, yoksa sürekli değişen bir varlık mıyız?', 'felsefe'),
('Sonsuzluk kavramı seni huzurlandırıyor mu korkutuyor mu?', 'felsefe'),

-- BİLİM (15 soru)
('Evrende yalnız olduğumuzu düşünüyor musun?', 'bilim'),
('Beyin mi bilinci yaratıyor yoksa bilinç mi beyni kullanıyor?', 'bilim'),
('Evrenin sonu hakkında ne düşünüyorsun?', 'bilim'),
('Işık hızında seyahat edebilsen ilk nereye giderdin?', 'bilim'),
('Kuantum fiziği günlük hayatımızı nasıl etkiliyor olabilir?', 'bilim'),
('Yapay organ ve uzuv teknolojisi insanlığı nereye götürür?', 'bilim'),
('Dünya dışı yaşam bulunsa toplum nasıl tepki verir?', 'bilim'),
('İnsan genomunu düzenlemek etik mi?', 'bilim'),
('Seni en çok şaşırtan bilimsel gerçek nedir?', 'bilim'),
('Mars''ta bir koloni kurulsa gider misin?', 'bilim'),
('Okyanusların derinlikleri uzaydan daha mı gizemli?', 'bilim'),
('Zamanda yolculuk mümkün olsa geçmişe mi gidersin geleceğe mi?', 'bilim'),
('Dünyadaki en küçük canlı bile bu kadar karmaşıkken basitlik nedir?', 'bilim'),
('Yerçekimi olmasaydı hayat nasıl olurdu?', 'bilim'),
('İklim değişikliğini durdurmak için bireysel olarak ne yapılabilir?', 'bilim'),

-- SANAT (15 soru)
('Bir kitap hayatını değiştirebilir mi? Hangisi değiştirdi?', 'sanat'),
('Sanat lüks mü yoksa temel ihtiyaç mı?', 'sanat'),
('Hangi sanat eseri seni derinden etkiledi?', 'sanat'),
('Yazarak kendini ifade etmek ile konuşarak ifade etmek arasındaki fark ne?', 'sanat'),
('Bir tablo senin yerine konuşabilseydi ne derdi?', 'sanat'),
('Şiir neden insanları bu kadar derinden etkiler?', 'sanat'),
('Sanatçının eseri mi sanatçıyı tanımlar, sanatçı mı eseri?', 'sanat'),
('Renklerin duyguları etkilediğine inanıyor musun?', 'sanat'),
('Hayatından bir sahneyi tablo yapsan nasıl görünürdü?', 'sanat'),
('Bir müzede sonsuza kadar kalabilecek olsan hangisini seçerdin?', 'sanat'),
('Fotoğrafçılık mı yoksa resim mi daha iyi anlatır?', 'sanat'),
('Sokak sanatı gerçek sanat mıdır?', 'sanat'),
('Güzellik evrensel mi yoksa kültürel mi?', 'sanat'),
('Dijital sanat geleneksel sanatın yerini alabilir mi?', 'sanat'),
('Hayatın kendisi bir sanat eseri olabilir mi?', 'sanat'),

-- TEKNOLOJİ (15 soru)
('Yapay zekanın yaratıcılığı gerçek yaratıcılık mıdır?', 'teknoloji'),
('Teknoloji insanları birbirine yaklaştırıyor mu uzaklaştırıyor mu?', 'teknoloji'),
('Telefonun olmadan bir hafta geçirebilir misin?', 'teknoloji'),
('Robotlar bir gün duygulara sahip olabilir mi?', 'teknoloji'),
('İnternetin icadından önceki hayatı hayal edebiliyor musun?', 'teknoloji'),
('Hangi teknoloji henüz icat edilmedi ama olmalı?', 'teknoloji'),
('Dijital kimliğin gerçek kimliğinden farklı mı?', 'teknoloji'),
('Otonom araçlara güvenir misin?', 'teknoloji'),
('Veri gizliliği için nelerden vazgeçebilirsin?', 'teknoloji'),
('Metaverse gerçek hayatın yerini alabilir mi?', 'teknoloji'),
('Yapay zeka sanatçıların işini elinden alır mı?', 'teknoloji'),
('Blockchain günlük hayatımızı nasıl değiştirecek?', 'teknoloji'),
('Bir uygulamayı tasarlayabilsen ne işe yarardı?', 'teknoloji'),
('Ekran süreni takip ediyor musun? Sonuçlar seni şaşırtıyor mu?', 'teknoloji'),
('Gelecekte hangi meslek tamamen otomatikleşecek?', 'teknoloji'),

-- HAYAT (15 soru)
('Hayatında en çok hangi karar seni şekillendirdi?', 'hayat'),
('Bugün baştan başlayabilsen neyi farklı yapardın?', 'hayat'),
('Seni en çok ne motive ediyor?', 'hayat'),
('Comfort zone''dan en son ne zaman çıktın?', 'hayat'),
('10 yıl önceki haline ne söylerdin?', 'hayat'),
('Mutluluğun formülü var mı?', 'hayat'),
('Başarısızlıklarından ne öğrendin?', 'hayat'),
('Hayatta en çok neye değer veriyorsun?', 'hayat'),
('En son ne zaman ilk kez bir şey denedin?', 'hayat'),
('Alışkanlıkların seni mi yönetiyor, sen mi onları?', 'hayat'),
('Yalnızlık ile yalnız olmak arasındaki fark ne?', 'hayat'),
('Sabahları kalkmak için en büyük motivasyonun ne?', 'hayat'),
('Hayatında hangi küçük an büyük bir fark yarattı?', 'hayat'),
('Dünyanın herhangi bir yerinde yaşayabilsen nerede yaşardın?', 'hayat'),
('Minnet duyduğun ama hiç söylemediğin şey ne?', 'hayat'),

-- TARİH (14 soru)
('Geçmişte yaşamak isteyeceğin bir dönem var mı?', 'tarih'),
('Tarihteki hangi kişiyle yemek yerdin?', 'tarih'),
('Osmanlı İmparatorluğu''ndan günümüze kalan en değerli miras ne?', 'tarih'),
('Tarih tekerrür mü eder yoksa biz mi öğrenmiyoruz?', 'tarih'),
('20. yüzyılın en önemli icadı hangisi?', 'tarih'),
('Antik medeniyetlerden öğrenebileceğimiz bir ders var mı?', 'tarih'),
('Savaşlar olmadan tarih yazılabilir miydi?', 'tarih'),
('Atatürk''ün en az bilinen reformu hangisi sence?', 'tarih'),
('100 yıl sonra bugünü nasıl hatırlayacaklar?', 'tarih'),
('İpek Yolu''nun modern versiyonu ne olabilir?', 'tarih'),
('Tarihteki hangi olay farklı olsaydı bugün dünya nasıl olurdu?', 'tarih'),
('Matbaanın icadı mı internet kadar devrimci miydi?', 'tarih'),
('Kadınların tarihte görünmez kaldığı alanlar neler?', 'tarih'),
('Anadolu''nun en gizemli tarihi yeri neresi?', 'tarih'),

-- SPOR (14 soru)
('Spor yapmak zihinsel sağlığını nasıl etkiliyor?', 'spor'),
('Hayatında hiç bir spor anı seni derinden etkiledi mi?', 'spor'),
('E-spor geleneksel sporlarla aynı saygıyı hak ediyor mu?', 'spor'),
('Bireysel spor mu takım sporu mu sana daha çok şey öğretiyor?', 'spor'),
('Olimpiyatların ruhu hâlâ yaşıyor mu?', 'spor'),
('Sporda yenilgi mi yoksa hiç denememiş olmak mı daha acı?', 'spor'),
('Bir spor dalını sıfırdan öğrenebilsen hangisi olurdu?', 'spor'),
('Sporcuların toplum üzerindeki etkisi ne kadar büyük?', 'spor'),
('Fair play sadece sporda mı geçerli?', 'spor'),
('Koşmak seni nereye götürür — sadece fiziksel olarak değil?', 'spor'),
('Spor ve disiplin arasındaki bağ hayatın diğer alanlarına nasıl yansıyor?', 'spor'),
('Dünya Kupası neden milyarlarca insanı birleştirebiliyor?', 'spor'),
('Doğada yapılan spor ile salon sporu arasındaki fark ne?', 'spor'),
('Bir maratona katılmak seni nasıl değiştirirdi?', 'spor'),

-- SOSYAL MEDYA (14 soru)
('Sosyal medya kişiliğin mi yoksa kişiliğinin filtreli hali mi?', 'sosyal-medya'),
('Beğeni sayısı gerçekten önemli mi?', 'sosyal-medya'),
('Sosyal medyasız bir dünya hayal edebilir misin?', 'sosyal-medya'),
('Çevrimiçi tartışmalar bir şeyi değiştirir mi?', 'sosyal-medya'),
('FOMO (bir şeyleri kaçırma korkusu) seni etkiliyor mu?', 'sosyal-medya'),
('Influencer kültürü topluma ne katıyor ne götürüyor?', 'sosyal-medya'),
('Dijital detox denedin mi? Nasıl hissettin?', 'sosyal-medya'),
('Paylaştığın içerikler gerçek hayatını ne kadar yansıtıyor?', 'sosyal-medya'),
('Sosyal medya demokrasiyi güçlendiriyor mu zayıflatıyor mu?', 'sosyal-medya'),
('Anonim olmak insanları daha mı dürüst yapıyor?', 'sosyal-medya'),
('Algoritma senin için mi çalışıyor sana karşı mı?', 'sosyal-medya'),
('Çocukların sosyal medya kullanması sınırlandırılmalı mı?', 'sosyal-medya'),
('Bir gün tüm sosyal medya hesaplarını silsen ne olur?', 'sosyal-medya'),
('İnternette viral olan bir şey seni son zamanlarda düşündürdü mü?', 'sosyal-medya'),

-- OYUN (14 soru)
('Oyunlar sadece eğlence mi yoksa bir sanat formu mu?', 'oyun'),
('Hayatında en çok iz bırakan oyun hangisi?', 'oyun'),
('Oyunlardaki hikayeler kitap veya film kadar güçlü olabilir mi?', 'oyun'),
('Rekabetçi oyun oynamak sana ne öğretti?', 'oyun'),
('Bir oyun dünyasında yaşayabilsen hangisini seçerdin?', 'oyun'),
('Oyun bağımlılığı ile tutku arasındaki çizgi nerede?', 'oyun'),
('Çocukken oynadığın oyunlar seni nasıl şekillendirdi?', 'oyun'),
('Masa oyunları mı dijital oyunlar mı daha çok bağ kuruyor?', 'oyun'),
('Bir oyun tasarlayabilsen konusu ne olurdu?', 'oyun'),
('Oyunlarda kaybetmeyi kabullenmek hayatta da işe yarıyor mu?', 'oyun'),
('Retro oyunların büyüsü nerede? Grafikler mi nostalji mi?', 'oyun'),
('Oyunlar empati kurmayı öğretebilir mi?', 'oyun'),
('Sandbox mı linear mı — özgürlük mü anlatı mı tercih edersin?', 'oyun'),
('Oyun müzikleri neden bu kadar akılda kalıcı?', 'oyun'),

-- MÜZİK (14 soru)
('Müzik olmadan bir dünya hayal edebilir misin?', 'muzik'),
('Bir şarkı seni son zamanlarda ağlattı mı?', 'muzik'),
('Müzik zevkin 5 yıl öncekiyle aynı mı?', 'muzik'),
('Bir enstrüman çalabilsen hangisi olurdu?', 'muzik'),
('Müzik neden anıları bu kadar canlı geri getirir?', 'muzik'),
('Canlı konser mi stüdyo kaydı mı?', 'muzik'),
('Şarkı sözleri mi melodi mi daha önemli?', 'muzik'),
('Müzik türleri arasında sınır kaldı mı?', 'muzik'),
('Yapay zeka ile üretilen müzik gerçek müzik sayılır mı?', 'muzik'),
('Sessizliğin de bir müziği var mı?', 'muzik'),
('Hayatının film müziği nasıl olurdu?', 'muzik'),
('Müzik insanları birleştiren en güçlü araç mı?', 'muzik'),
('Bir dönemin müziği o dönemi nasıl yansıtır?', 'muzik'),
('Kulaklıkla dinlemek mi hoparlörle mi — fark ne?', 'muzik'),

-- SİNEMA (14 soru)
('Bir film hayatına bakış açını değiştirdi mi?', 'sinema'),
('Kötü adam mı iyi yazılmış yoksa iyi adam mı? Hangisi daha zor?', 'sinema'),
('Kitaptan uyarlanan filmler neden genelde hayal kırıklığı yaratır?', 'sinema'),
('Sinema salonunda film izlemenin büyüsü nerede?', 'sinema'),
('Bir film yönetmeni olsan ilk filmin ne hakkında olurdu?', 'sinema'),
('Belgeseller kurgu filmlerden daha mı etkileyici?', 'sinema'),
('Türk sinemasının dünyaya söyleyecek sözü var mı?', 'sinema'),
('Bir filmi tekrar tekrar izlemeni sağlayan şey ne?', 'sinema'),
('Animasyon filmler sadece çocuklar için mi?', 'sinema'),
('Bir film karakteriyle yer değiştirebilsen kim olurdu?', 'sinema'),
('Streaming platformları sinemayı öldürüyor mu?', 'sinema'),
('Film müziği filmin yarısını mı oluşturur?', 'sinema'),
('En sevdiğin film repliği hangisi ve neden?', 'sinema'),
('Korku filmleri neden bu kadar çekici?', 'sinema'),

-- YEMEK (14 soru)
('Yemek pişirmek bir meditasyon biçimi olabilir mi?', 'yemek'),
('Annenin veya babanın yaptığı en özlediğin yemek hangisi?', 'yemek'),
('Bir ülkenin mutfağı o kültür hakkında ne söyler?', 'yemek'),
('Sokak yemeği mi fine dining mı?', 'yemek'),
('Veganlık bir trend mi yoksa gelecek mi?', 'yemek'),
('Yemek yerken telefon kullanmamak hayatını nasıl değiştirir?', 'yemek'),
('Bir yemek tarifi icat edebilsen ne olurdu?', 'yemek'),
('Çay mı kahve mi — ve neden?', 'yemek'),
('Gıda israfını azaltmak için bireysel olarak ne yapılabilir?', 'yemek'),
('Yemek yemek sosyal bir eylem mi yoksa bireysel bir ihtiyaç mı?', 'yemek'),
('Dünyada tatmak istediğin bir yemek var mı?', 'yemek'),
('Bir sofrada en önemli şey yemek mi yoksa sohbet mi?', 'yemek'),
('Baharatsız bir dünya hayal edebilir misin?', 'yemek'),
('Ekmek neden bu kadar evrensel bir yiyecek?', 'yemek'),

-- PSİKOLOJİ (14 soru)
('Kendine en son ne zaman "neden böyle hissediyorum?" diye sordun?', 'psikoloji'),
('Alışkanlık değiştirmek neden bu kadar zor?', 'psikoloji'),
('İlk izlenim ne kadar güvenilir?', 'psikoloji'),
('Stresle başa çıkma yöntemin ne?', 'psikoloji'),
('İnsanlar neden erteleme yapar?', 'psikoloji'),
('Empati öğrenilebilir mi?', 'psikoloji'),
('Rüyaların sana bir şey söylemeye çalıştığını düşünüyor musun?', 'psikoloji'),
('Nostalji neden tatlı bir acıdır?', 'psikoloji'),
('Kendini başkalarıyla kıyaslamayı nasıl bırakırsın?', 'psikoloji'),
('Beden dili sözlerden daha mı dürüst?', 'psikoloji'),
('Psikolojik dayanıklılık doğuştan mı yoksa geliştirilir mi?', 'psikoloji'),
('Bir korkunu yendiğin an nasıl hissettin?', 'psikoloji'),
('İnsanlar neden kötü haberlere daha çok ilgi gösterir?', 'psikoloji'),
('Kendi kendine konuşmak normal mi?', 'psikoloji'),

-- DOĞAL YAŞAM (14 soru)
('Doğada geçirdiğin en huzurlu an hangisiydi?', 'dogal-yasam'),
('Bir hayvanın gözünden dünyayı görebilsen hangisini seçerdin?', 'dogal-yasam'),
('Şehir hayatı doğadan ne kadar kopardı bizi?', 'dogal-yasam'),
('Bir ağaç dikmek dünyayı gerçekten değiştirir mi?', 'dogal-yasam'),
('Deniz mi dağ mı — ve bu tercih senin hakkında ne söylüyor?', 'dogal-yasam'),
('Nesli tükenen bir türü kurtarabilsen hangisi olurdu?', 'dogal-yasam'),
('Mevsimler ruh halini etkiliyor mu?', 'dogal-yasam'),
('Sürdürülebilir yaşam için en kolay adım ne?', 'dogal-yasam'),
('Gece gökyüzüne en son ne zaman baktın?', 'dogal-yasam'),
('Evcil hayvanlar insanların hayatına ne katıyor?', 'dogal-yasam'),
('Bir hafta boyunca ormanda yaşayabilir misin?', 'dogal-yasam'),
('Doğanın sesi en güzel nerede duyulur?', 'dogal-yasam'),
('Plastik kullanımını tamamen bırakmak mümkün mü?', 'dogal-yasam'),
('Gelecek nesillere nasıl bir dünya bırakıyoruz?', 'dogal-yasam'),

-- ============================================
-- EK SORU PAKETİ (365+ Gün Hedefi)
-- ============================================

-- EBEDİ TARTIŞMALAR (Popüler Karşılaştırmalar - 30 soru)
('Ronaldo mu, Messi mi? Yetenek mi, çalışma mı?', 'tartisma'),
('Marvel mı, DC mi? Kusursuz kahramanlar mı, karanlık dünyalar mı?', 'tartisma'),
('PC mi, Konsol mu? Özgürlük mü, konfor mu?', 'tartisma'),
('iPhone mu, Android mi? Ekosistem mi, kişiselleştirme mi?', 'tartisma'),
('Star Wars mı, Lord of the Rings mi?', 'tartisma'),
('Batman mi, Joker mi? Adalet mi, kaos mu?', 'tartisma'),
('Çay mı, Kahve mi? Ayılmak mı, dinlenmek mi?', 'tartisma'),
('Deniz tatili mi, Kayak tatili mi?', 'tartisma'),
('Pizzada ananas olur mu, olmaz mı?', 'tartisma'),
('Kitabı okumak mı, filmi izlemek mi?', 'tartisma'),
('Tupac mı, Biggie mi? Batı yakası mı, Doğu yakası mı?', 'tartisma'),
('Diziler mi, Filmler mi? Uzun soluklu bağ mı, vurucu final mi?', 'tartisma'),
('Harry Potter mı, Yüzüklerin Efendisi mi?', 'tartisma'),
('Nike mı, Adidas mı?', 'tartisma'),
('Beatles mı, Queen mi?', 'tartisma'),
('Kedi mi, Köpek mi?', 'tartisma'),
('Yaz mı, Kış mı?', 'tartisma'),
('Gece insanı mı, Sabah insanı mı?', 'tartisma'),
('Star Trek mi, Star Wars mu?', 'tartisma'),
('Formula 1 mi, Moto GP mi?', 'tartisma'),
('Spotify mı, Apple Music mi?', 'tartisma'),
('Netflix mi, sinema salonu mu?', 'tartisma'),
('Köy hayatı mı, şehir hayatı mı?', 'tartisma'),
('Süpermen mi, Goku mu?', 'tartisma'),
('Sabah duşu mu, akşam duşu mu?', 'tartisma'),
('Tatlı mı, tuzlu mu?', 'tartisma'),
('Kalem mi, klavye mi?', 'tartisma'),
('Siyah mı, beyaz mı — favori non-renk?', 'tartisma'),
('Fizik kitabı mı, felsefe kitabı mı?', 'tartisma'),
('Otobüs mü, tren mi?', 'tartisma'),

-- 2026 GELECEK VE TEKNOLOJİ EKLEMELERİ (20 soru)
('Kendi dijital ikizin olsa, onu senin yerine okula veya işe gönderir miydin?', 'teknoloji'),
('Yapay zeka bir gün bir "ruh" sahibi olabilir mi?', 'teknoloji'),
('Gözlerine takılan bir lensle tüm dünyayı filtreli görseydin, gerçeklik algın nasıl değişirdi?', 'teknoloji'),
('Uçan arabalar mı, yoksa ışınlanma mı daha büyük bir devrim olurdu?', 'teknoloji'),
('Bir yapay zeka tarafından yazılmış bir kitaba ağlayabilir misin?', 'sanat'),
('Kripto paralar fiziksel parayı tamamen bitirecek mi?', 'teknoloji'),
('Kendi genetiğini tasarlayabilseydin, değiştireceğin ilk özelliğin ne olurdu?', 'bilim'),
('Mars''ta doğan ilk çocuk dünyalı mıdır, Marslı mı?', 'bilim'),
('Beynindeki anıları bir USB belleğe yedeklemek ister miydin?', 'teknoloji'),
('Hangi mesleğin asla yapay zeka tarafından yapılamayacağını düşünüyorsun?', 'teknoloji'),
('Sanal gerçeklikte yediğin bir yemeğin tadını alsaydın, gerçek yemekten vazgeçer miydin?', 'yemek'),
('Bir robotun sanık sandalyesine oturduğu bir mahkemede jüri olur muydun?', 'bilim'),
('Gelecekte insanlar sadece internet üzerinden mi sosyalleşecek?', 'sosyal-medya'),
('Hangi teknolojik icat insanlığı tembelleştirdi?', 'teknoloji'),
('Yapay zekanın yönettiği bir ülke daha mı adil olurdu?', 'felsefe'),
('Hologram teknolojisi uzaktaki sevdiklerinle görüşmeyi nasıl değiştirir?', 'teknoloji'),
('Nörolink gibi beyin-bilgisayar arayüzleri korkutucu mu heyecan verici mi?', 'teknoloji'),
('Bir algoritma seni senden daha iyi tanıyabilir mi?', 'teknoloji'),
('3D yazıcılar bir gün ev yapımı yemeğin yerini alır mı?', 'teknoloji'),
('Kuantum bilgisayarlar şifreleme dünyasını nasıl alt üst edecek?', 'bilim'),

-- DERİN HAYAT VE PSİKOLOJİ (25 soru)
('Seni sen yapan şey nedir? İsmin mi, anıların mı, yoksa bedenin mi?', 'felsefe'),
('En büyük korkunla yüzleşmek mi, yoksa onunla sonsuza kadar yaşamak mı?', 'psikoloji'),
('Başkalarına yardım etmek mi seni daha çok mutlu eder, yoksa kendine yatırım yapmak mı?', 'hayat'),
('Bir gününü tekrar yaşayabilseydin, hangi günü seçerdin?', 'hayat'),
('Geleceği bilmek mi istersin, yoksa geçmişi değiştirmek mi?', 'hayat'),
('Suskunluk bir cevap mıdır?', 'psikoloji'),
('Hayal kurmak bir kaçış mı, yoksa bir hazırlık mı?', 'psikoloji'),
('En son ne zaman kendine "Aferin" dedin?', 'psikoloji'),
('Başkalarının senin hakkındaki düşünceleri ne kadar senin gerçeğin?', 'psikoloji'),
('Affetmek mi daha zordur, unutmak mı?', 'psikoloji'),
('Hayatındaki en büyük "iyi ki" dediğin olay ne?', 'hayat'),
('Birini sevmek için onu tamamen tanımak mı gerekir?', 'psikoloji'),
('Mutluluk satın alınabilir mi?', 'felsefe'),
('Zamanı durdurabilseydin, o an ne yapıyor olurdun?', 'hayat'),
('Kendine verdiğin en büyük sözü tuttun mu?', 'psikoloji'),
('İnsanlar neden değişmekten bu kadar korkar?', 'psikoloji'),
('Hayatında kimin sözü seni en çok etkiledi?', 'hayat'),
('Yalnız seyahat etmek cesaret mi, yoksa kaçış mı?', 'hayat'),
('Bir mektup yazsaydın — 10 yıl sonraki kendine — ne derdin?', 'hayat'),
('Gülmek mi ağlamak mı daha çok rahatlatıyor?', 'psikoloji'),
('Rutinler güvenlik mi sağlar yoksa hapishane mi?', 'psikoloji'),
('Birini kaybetmek seni nasıl değiştirdi?', 'hayat'),
('Dürüstlük her zaman en iyi politika mıdır?', 'felsefe'),
('Pişmanlıkların seni güçlendirdi mi yoksa zayıflattı mı?', 'hayat'),
('Kendini en özgür hissettiğin an neydi?', 'hayat'),

-- OYUN, SPOR VE HOBİ EKLEMELERİ (25 soru)
('Football Manager mı, FIFA (FC) mi?', 'oyun'),
('LeBron James mi, Michael Jordan mı? GOAT kim?', 'spor'),
('Bir e-spor takımı kuracak olsan adını ne koyardın?', 'oyun'),
('Dark Souls mu, Elden Ring mi? Zorluk mu, keşif mi?', 'oyun'),
('Satranç mı, Tavla mı? Strateji mi, şans mı?', 'oyun'),
('Hangi oyun karakterinin hayatını yaşamak isterdin?', 'oyun'),
('Spor yapmak mı daha keyifli, spor izlemek mi?', 'spor'),
('Milli takım şampiyonluğu mu, tuttuğun takımın şampiyonluğu mu?', 'spor'),
('Bir spor dalında dünya rekoru kırabilecek olsan hangisini seçerdin?', 'spor'),
('Basketbol mu, Futbol mu?', 'spor'),
('Yalnız oynamak mı, multiplayer mı?', 'oyun'),
('Oyun hileleri oyun zevkini bitirir mi?', 'oyun'),
('Zeka oyunları mı, refleks oyunları mı?', 'oyun'),
('Stadyumda maç izlemek mi, evde izlemek mi?', 'spor'),
('GTA mı, Red Dead Redemption mı?', 'oyun'),
('Minecraft mı, Terraria mı?', 'oyun'),
('Olimpiyatlarda en çok hangi sporu izlemeyi seviyorsun?', 'spor'),
('Bir dövüş sanatı öğrenecek olsan hangisi olurdu?', 'spor'),
('Hayatında en çok eğlendiğin masa oyunu hangisi?', 'oyun'),
('Yüzme mi, koşma mı — hangisi daha iyi terapi?', 'spor'),
('Bir oyunda en çok ne önemli: grafik mi, hikaye mi, gameplay mi?', 'oyun'),
('Takım kaptanı olmak mı istersin yoksa yıldız oyuncu mu?', 'spor'),
('Zelda mı, Mario mu?', 'oyun'),
('Yoga mı, ağırlık mı — zihin mi beden mi önce?', 'spor'),
('Hangi spor dalı hak ettiği ilgiyi görmüyor?', 'spor'),

-- KISA VE VURUCU GÜNLÜK SORULAR (25 soru)
('Bugün seni en çok ne gülümsetti?', 'hayat'),
('Şu an çalan şarkı senin modunu nasıl etkiliyor?', 'muzik'),
('Günün en güzel saati hangisi?', 'hayat'),
('Bugün öğrendiğin en ilginç bilgi ne?', 'bilim'),
('Yarın uyandığında bir süper gücün olsa, ne olsun isterdin?', 'hayat'),
('Hangi kokuyu duyduğunda çocukluğuna gidiyorsun?', 'psikoloji'),
('Şu an yanında kimin olmasını isterdin?', 'hayat'),
('Kendini bir emojiyle anlatsan hangisi olurdun?', 'sosyal-medya'),
('Bugün hiç kimseye söylemediğin bir düşüncen var mı?', 'psikoloji'),
('Hayatının şu anki bölümüne bir isim versen ne olurdu?', 'hayat'),
('Bu sabah pencereden ilk ne gördün?', 'dogal-yasam'),
('Telefonundaki son fotoğraf ne? Neden çektin?', 'sosyal-medya'),
('Bugün birinin gününü güzelleştirecek ne yapabilirsin?', 'hayat'),
('Son gördüğün rüyayı hatırlıyor musun?', 'psikoloji'),
('Şu an dünyanın neresinde olmak isterdin?', 'hayat'),
('Bugün ne yesen mutlu olursun?', 'yemek'),
('Son okuduğun kitaptan aklında ne kaldı?', 'sanat'),
('Bu hafta sonu planın ne?', 'hayat'),
('Birini güldürmek mi daha kolay, düşündürmek mi?', 'psikoloji'),
('En son ne zaman gökyüzüne baktın ve "vay" dedin?', 'dogal-yasam'),
('Şu an hangi duygudasın — tek kelimeyle?', 'psikoloji'),
('Hayatındaki en iyi öğretmen kim oldu?', 'hayat'),
('Bir podcast dinlesen konu ne olsun isterdin?', 'teknoloji'),
('Akşam yemeğinde dünyadan birini davet edebilsen kim olurdu?', 'hayat'),
('Bugünün bir rengi olsaydı ne olurdu?', 'sanat'),

-- MÜZİK VE SİNEMA EKLEMELERİ (20 soru)
('Bir konser organize edebilsen line-up''ta kimler olurdu?', 'muzik'),
('Hayatının soundtrack''i hangi 3 şarkıdan oluşurdu?', 'muzik'),
('Bir film sahnesinde yer alabilsen hangi sahne olurdu?', 'sinema'),
('Türkçe rap mi, Türkçe pop mu?', 'muzik'),
('Nolan mı, Tarantino mu?', 'sinema'),
('Bir dönemin müziği geri gelebilse hangi dönem?', 'muzik'),
('Hayatındaki en iyi konser deneyimi neydi?', 'muzik'),
('Bir film yapımcısı olsan hangi türde film çekerdin?', 'sinema'),
('Korku filmi mi, gerilim mi — hangisi daha zekice?', 'sinema'),
('Bir albümü baştan sona dinleme alışkanlığın var mı?', 'muzik'),
('En iyi film serisi hangisi?', 'sinema'),
('Bir şarkı sözü hayat felsefeni özetleyebilseydi hangisi olurdu?', 'muzik'),
('Sessiz sinema dönemine bir film çekseydin konusu ne olurdu?', 'sinema'),
('Bir belgesel konusu önerecek olsan ne hakkında olurdu?', 'sinema'),
('Bir soundtrack seni en son ne zaman ağlattı?', 'sinema'),
('Caz mı, Rock mı, Elektronik mi?', 'muzik'),
('Favori film villain''ın kim?', 'sinema'),
('Vinyl mi, dijital mi — müzik nasıl daha iyi duyulur?', 'muzik'),
('Komedi filmleri neden drama kadar ciddiye alınmıyor?', 'sinema'),
('Bir karaoke şarkın var mı? Hangisi?', 'muzik'),

-- SOSYAL MEDYA VE DİJİTAL KÜLTÜR EKLEMELERİ (15 soru)
('En çok vakit geçirdiğin uygulama hangisi ve bu seni mutlu mu ediyor?', 'sosyal-medya'),
('Twitter/X mi, Reddit mi — bilgi için hangisi?', 'sosyal-medya'),
('TikTok dikkat süremizi kısalttı mı?', 'sosyal-medya'),
('Bir influencer olsan hangi alanda içerik üretirdin?', 'sosyal-medya'),
('YouTube''da en son ne zaman saatlerce kaybolduğunu fark ettin?', 'sosyal-medya'),
('İnternet kültürü 50 yıl sonra nasıl hatırlanacak?', 'sosyal-medya'),
('Meme kültürü modern sanat mıdır?', 'sosyal-medya'),
('Online arkadaşlıklar gerçek arkadaşlıklar kadar değerli mi?', 'sosyal-medya'),
('Cancel culture adil mi?', 'sosyal-medya'),
('Bir hafta boyunca sadece bir uygulama kullanabilsen hangisi olurdu?', 'sosyal-medya'),
('Profilindeki fotoğraf gerçek seni mi yansıtıyor?', 'sosyal-medya'),
('Deepfake teknolojisi güveni nasıl etkiliyor?', 'sosyal-medya'),
('İnternet olmasaydı bu nesil nasıl büyürdü?', 'sosyal-medya'),
('LinkedIn kültürü samimi mi yoksa performans mı?', 'sosyal-medya'),
('BeReal gibi uygulamalar gerçekliğe dönüş mü?', 'sosyal-medya'),

-- YEMEK VE DOĞAL YAŞAM EKLEMELERİ (15 soru)
('Ev yemeği mi, dışarıda yemek mi — ve neden?', 'yemek'),
('Bir ülkenin mutfağını tamamen keşfedebilsen hangisi olurdu?', 'yemek'),
('Kahvaltı en önemli öğün müdür gerçekten?', 'yemek'),
('Bir tarifi mükemmelleştirmek için kaç kez denemen gerekir?', 'yemek'),
('Fast food suçlu zevk mi yoksa kültürel bir olgu mu?', 'yemek'),
('Günbatımı mı, gündo ğumu mu — hangisi daha etkileyici?', 'dogal-yasam'),
('Bir nehrin kıyısında saatlerce oturabilir misin?', 'dogal-yasam'),
('Şehirde kuş sesi duymak seni şaşırtıyor mu?', 'dogal-yasam'),
('Bahçe işleriyle uğraşmak meditasyon sayılır mı?', 'dogal-yasam'),
('Yağmur sesi neden bu kadar huzur verici?', 'dogal-yasam'),
('Kamp yapmak lüks mü yoksa ilkel mi?', 'dogal-yasam'),
('Dünyadaki en güzel doğal manzara nerede?', 'dogal-yasam'),
('Bir hayvanla konuşabilsen hangisiyle ve ne sorardın?', 'dogal-yasam'),
('Denizaltı dünyasını keşfetmek mi, uzayı mı?', 'dogal-yasam'),
('Toprağa dokunmak seni sakinleştirir mi?', 'dogal-yasam');
